services:
  database:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    env_file:
      - ./packages/api/.env.production
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - database
    expose:
      - "3000"
    restart: unless-stopped

  # Build and serve the front directly
  reverse-proxy:
    image: nginx:alpine
    build:
      context: .
      dockerfile: ./packages/front/Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped

volumes:
  mongo_data:
