version: "3.8"

services:
  # Fastify API Service
  api:
    volumes:
      - ./api:/app
    environment:
      - PORT=3000
    expose:
      - "3000"
    command: sh -c "npm install && npm run dev"

  # Vue.js App Service
  front:
    volumes:
      - ./app:/app
    environment:
      - PORT=5173
    expose:
      - "5173"
    command: sh -c "npm install && npm run dev"