version: "3.8"

services:
  database:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - database
    expose:
      - "3000"

  front:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "80"

  reverse-proxy:
    image: nginx:alpine
    depends_on:
      - api
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro

volumes:
  mongo_data:
